# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kpackage': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kauth': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'plasma/libplasma': '@same'
    'plasma/layer-shell-qt': '@same'
    'plasma/plasma-workspace': '@same'

Options:
 cmake-options: "-DUID_MIN=1000 -DUID_MAX=60000"
 run-qmllint: true
